### PR TITLE
Change path condition to match a provided regex, not a simple string.startswith

### PR DESCRIPTION
**Pull request by Scotchester**
Per discussion in #17.

### CODE REVIEW

**Comment by Scotchester** [comment]
@willbarton I have no idea how to go about doing that :)

**Comment by willbarton** [comment]
@Scotchester heh, I'll see if I can throw something together.

**Comment by Scotchester** [comment]
@willbarton @chosak Updated to add the data migration and a test for it. Ready for re-review!

**Comment by willbarton** [comment]
@Scotchester This is a fantastic change! Thanks!

**Comment by Scotchester** [comment]
Woohoon

**Comment by Scotchester** [comment]
I'd like to note that I'm not sure what needs to happen to get this released :)

**Comment by Scotchester** [comment]
🛎 @willbarton @chosak

**Comment by chosak** [comment]
@Scotchester as a reward for your persistence, this functionality is now available in release 2.0.7, [now available on PyPI](https://pypi.python.org/pypi/wagtail-flags/2.0.7).

**Comment by Scotchester** [comment]
Thank you :)

**Pull request merged**
